alias gr="./gradlew"
alias v='fasd -e nvim' # quick opening files with nvim
alias z='fasd_cd -d'
alias at='fasd -e atom'
alias tmux='tmux -2'
alias dm='docker-machine'
alias vim='nvim'
alias ku='kubectl'
alias ll='ls -la'
