font_family Menlo Regular
font_size 11.5
allow_remote_control yes
listen_on unix:/tmp/kitty
shell_integration enabled
scrollback_lines -1

map ctrl+shift+h neighboring_window left
map ctrl+shift+l neighboring_window right
map ctrl+shift+k neighboring_window up
map ctrl+shift+j neighboring_window down
enabled_layouts tall,stack
map command+z toggle_layout stack

include ~/.config/kitty/themes/snazzy.conf
ap ctrl+shift+h neighboring_window left
map ctrl+shift+l neighboring_window right
map ctrl+shift+k neighboring_window up
map ctrl+shift+j neighboring_window down
enabled_layouts tall,stack
map command+z toggle_layout stack

scrollback_lines -1


font_family Menlo Regular
font_size 11.5

allow_remote_control yes
listen_on unix:/tmp/kitty
shell_integration enabled

#allow_remote_control socket-only
#map command+f kitty_scrollback_nvim

action_alias kitty_scrollback_nvim kitten /Users/alex.fortin/.local/share/nvim/lazy/kitty-scrollback.nvim/python/kitty_scrollback_nvim.py
map command+f kitty_scrollback_nvim

include snazzy.conf
